services:
    app:
        build: 
            context: ..
            dockerfile: Dockerfile
        container_name: receipt-app
        ports:
            - "8080:80"
        environment:
            APACHE_RUN_USER: www-data
            APACHE_RUN_GROUP: www-data
        volumes:
            - ../backend/keys:/var/www/html/keys:ro
        env_file:
            - ../.env
        working_dir: /var/www/html
