services:
    app:
        build: ./docker/php
        container_name: receipt-app
        ports:
            - "8080:80"
        environment:
            APACHE_RUN_USER: www-data
            APACHE_RUN_GROUP: www-data
        volumes:
            - ../frontend:/var/www/html
            - ../backend:/var/www/html/api:ro
            - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini:ro
            - ../backend/keys:/var/www/html/api/keys:ro
            - ../.eslintrc.js:/var/www/html/../.eslintrc.js:ro
            - ../phpcs.xml:/var/www/html/../phpcs.xml:ro
        env_file:
            - .env
        working_dir: /var/www/html
