name: Cache-busting automatique

on:
  # Déclenché manuellement
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement cible'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
      force:
        description: 'Forcer le cache-busting même sans changements'
        required: false
        default: false
        type: boolean

  # Déclenché sur modification des assets
  push:
    paths:
      - 'frontend/assets/**'
      - 'frontend/index.html'
    branches: [ main, staging ]

jobs:
  cache-bust:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Cache-busting automatique
        run: |
          echo "🔄 Cache-busting automatique..."
          chmod +x scripts/cache-bust-safe.sh
          ./scripts/cache-bust-safe.sh
          
          echo "📊 Vérification des changements:"
          git diff --name-only
          
          if git diff --quiet; then
            echo "ℹ️  Aucun changement détecté dans les assets"
            if [ "${{ github.event.inputs.force }}" = "true" ]; then
              echo "⚠️  Mode forcé activé - commit même sans changements"
            else
              echo "✅ Aucune action nécessaire"
              exit 0
            fi
          else
            echo "✅ Cache-busting appliqué avec succès"
          fi

      - name: Commit et push des changements
        if: github.event_name == 'workflow_dispatch' || !git diff --quiet
        run: |
          ENV="${{ github.event.inputs.environment || 'auto' }}"
          
          # Déterminer l'environnement basé sur la branche si non spécifié
          if [ "$ENV" = "auto" ]; then
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              ENV="production"
            elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
              ENV="staging"
            else
              ENV="development"
            fi
          fi
          
          echo "🎯 Environnement détecté: $ENV"
          
          git add frontend/index.html
          git commit -m "chore: cache-busting automatique pour $ENV [skip ci]" || echo "ℹ️  Pas de commit nécessaire"
          
          # Push seulement si on a fait un commit
          if git log -1 --pretty=%B | grep -q "chore: cache-busting"; then
            git push origin ${{ github.ref_name }}
            echo "✅ Changements poussés vers ${{ github.ref_name }}"
          fi

      - name: Notifier le résultat
        run: |
          if git log -1 --pretty=%B | grep -q "chore: cache-busting"; then
            echo "🎉 Cache-busting appliqué avec succès !"
            echo "📋 Environnement: ${{ github.event.inputs.environment || 'auto' }}"
            echo "🌿 Branche: ${{ github.ref_name }}"
          else
            echo "ℹ️  Aucun changement nécessaire"
          fi
