name: Credentials Security Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  credentials-security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Validate .gitignore
      run: |
        echo "📋 Vérification de .gitignore..."
        if ! grep -q "*.json" .gitignore; then
          echo "❌ .gitignore ne contient pas '*.json'"
          exit 1
        fi
        if ! grep -q "keys/" .gitignore; then
          echo "❌ .gitignore ne contient pas 'keys/'"
          exit 1
        fi
        if ! grep -q ".env" .gitignore; then
          echo "❌ .gitignore ne contient pas '.env'"
          exit 1
        fi
        echo "✅ .gitignore correctement configuré"
        
    - name: Check for sensitive patterns
      run: |
        echo "🔍 Recherche de patterns sensibles..."
        
        # Vérifier qu'il n'y a pas de clés privées
        if grep -r "-----BEGIN PRIVATE KEY-----" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=vendor --exclude="*.md" 2>/dev/null; then
          echo "❌ Clés privées trouvées dans le code"
          exit 1
        fi
        
        # Vérifier qu'il n'y a pas de secrets dans les fichiers
        if grep -r "client_secret" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=vendor --exclude="*.md" 2>/dev/null; then
          echo "❌ Secrets trouvés dans le code"
          exit 1
        fi
        
        # Vérifier qu'il n'y a pas de tokens
        if grep -r "refresh_token" . --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=vendor --exclude="*.md" 2>/dev/null; then
          echo "❌ Tokens trouvés dans le code"
          exit 1
        fi
        
        echo "✅ Aucun pattern sensible trouvé"
        
    - name: Check documentation
      run: |
        echo "📚 Vérification de la documentation..."
        
        # Vérifier que README.md existe
        if [ ! -f "README.md" ]; then
          echo "❌ README.md manquant"
          exit 1
        fi
        
        # Vérifier que README.md contient des informations sur les credentials
        if ! grep -q -i "credential" README.md; then
          echo "❌ README.md ne contient pas d'informations sur les credentials"
          exit 1
        fi
        
        echo "✅ Documentation présente"
        
    - name: Security summary
      run: |
        echo "🎉 Vérification de sécurité terminée avec succès !"
        echo "   - Aucun secret exposé"
        echo "   - .gitignore correctement configuré"
        echo "   - Documentation présente"
        echo "   - Repository sécurisé"
