name: Deploy with Secret Manager

on:
  workflow_dispatch:  # Désactivé pour les push automatiques, utilisez Cloud Build

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: false  # Workflow désactivé - utilisez Cloud Build à la place
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Info message
      run: |
        echo "ℹ️ Ce workflow est désactivé."
        echo "Le déploiement se fait via Cloud Build triggers configurés sur GCP."
        echo "Pour déployer, utilisez le trigger Cloud Build ou poussez sur la branche main."
