name: Quality Checks

on:
  push:
    branches: [ main, staging, develop ]
  pull_request:
    branches: [ main, staging ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, xml, curl, zip
          tools: composer

      - name: Install PHP dependencies
        run: |
          cd backend
          composer install --no-dev --optimize-autoloader --no-interaction

      - name: Lint JavaScript
        run: |
          if [ -f ".eslintrc.js" ]; then
            npx eslint frontend/assets/js/app.js --config .eslintrc.js
          else
            echo "No ESLint config found, skipping JS lint"
          fi

      - name: Lint PHP
        run: |
          cd backend
          ./vendor/bin/phpcs --standard=../phpcs.xml .

      - name: Check file structure
        run: |
          echo "🔍 Checking file structure..."
          
          # Vérifier que frontend/ ne contient que de l'UI
          if find frontend/ -name "*.php" | grep -q .; then
            echo "❌ ERROR: frontend/ contains PHP files"
            exit 1
          fi
          
          # Vérifier que backend/ ne contient que de l'API
          if find backend/ -name "*.html" | grep -q .; then
            echo "❌ ERROR: backend/ contains HTML files"
            exit 1
          fi
          
          # Vérifier qu'aucun secret n'est commité
          if find . -name "*.json" -path "*/keys/*" | grep -q .; then
            echo "❌ ERROR: Secret files found in keys/"
            exit 1
          fi
          
          if grep -r "sk-" . --include="*.php" --include="*.js" --include="*.json" | grep -v "example\|test\|dummy" | grep -q .; then
            echo "❌ ERROR: Potential secret keys found in code"
            exit 1
          fi
          
          # Vérifier qu'il n'y a qu'un seul .htaccess (à la racine)
          htaccess_count=$(find . -name ".htaccess" | wc -l)
          if [ "$htaccess_count" -ne 1 ]; then
            echo "❌ ERROR: Found $htaccess_count .htaccess files, expected exactly 1 at root"
            find . -name ".htaccess" -exec echo "  Found: {}" \;
            exit 1
          fi
          
          # Vérifier que config.local.example n'existe plus (déplacé vers infra/.env.example)
          if [ -f "config.local.example" ]; then
            echo "❌ ERROR: config.local.example found, should be infra/.env.example"
            exit 1
          fi
          
          # Vérifier que infra/.env.example existe et contient les variables requises
          if [ ! -f "infra/.env.example" ]; then
            echo "❌ ERROR: infra/.env.example missing"
            exit 1
          fi
          
          required_vars=("GCP_PROJECT_ID" "GOOGLE_OAUTH_CLIENT_ID" "SPREADSHEET_ID" "ALLOWED_EMAILS" "GCP_PROCESSOR_ID")
          for var in "${required_vars[@]}"; do
            if ! grep -q "^${var}=" infra/.env.example; then
              echo "❌ ERROR: Required variable $var missing in infra/.env.example"
              exit 1
            fi
          done
          
          # Vérifier le format WHO_COLUMNS dans .env.example
          if grep -q "WHO_COLUMNS=" infra/.env.example; then
            who_columns_line=$(grep "WHO_COLUMNS=" infra/.env.example | head -1)
            if [[ ! "$who_columns_line" =~ WHO_COLUMNS=\{[^}]+\} ]]; then
              echo "❌ ERROR: WHO_COLUMNS format invalid in infra/.env.example"
              echo "Expected: WHO_COLUMNS={\"Name\":[\"A\",\"B\",\"C\"]}"
              echo "Found: $who_columns_line"
              exit 1
            fi
          fi
          
          echo "✅ File structure validation passed"

      - name: Check README
        run: |
          if [ ! -f "README.md" ]; then
            echo "❌ ERROR: README.md missing"
            exit 1
          fi
          
          # Vérifier que le README contient les sections importantes
          if ! grep -q "Architecture" README.md; then
            echo "❌ ERROR: README.md missing Architecture section"
            exit 1
          fi
          
          if ! grep -q "Développement Local" README.md; then
            echo "❌ ERROR: README.md missing Développement Local section"
            exit 1
          fi
          
          echo "✅ README validation passed"

      - name: Validation du cache-busting
        run: |
          echo "🔍 Validation du système de cache-busting..."
          
          # Vérifier que le script existe
          if [ ! -f "scripts/cache-bust-safe.sh" ]; then
            echo "❌ ERROR: scripts/cache-bust-safe.sh missing"
            exit 1
          fi
          
          # Vérifier que le script est exécutable
          if [ ! -x "scripts/cache-bust-safe.sh" ]; then
            echo "❌ ERROR: scripts/cache-bust-safe.sh not executable"
            exit 1
          fi
          
          # Vérifier que index.html contient des références versionnées
          if ! grep -q "app\.css\?v=" frontend/index.html; then
            echo "❌ ERROR: frontend/index.html missing versioned CSS reference"
            exit 1
          fi
          
          if ! grep -q "app\.js\?v=" frontend/index.html; then
            echo "❌ ERROR: frontend/index.html missing versioned JS reference"
            exit 1
          fi
          
          echo "✅ Cache-busting validation passed"

      - name: Summary
        run: |
          echo "✅ All quality checks passed!"
          echo "📊 Summary:"
          echo "  - JavaScript linting: ✅"
          echo "  - PHP linting: ✅"
          echo "  - Cache-busting validation: ✅"
          echo "  - File structure: ✅"
          echo "  - Security check: ✅"
          echo "  - Documentation: ✅"
